import { createHash, randomUUID } from "node:crypto";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/db";
import type { CommercialActor } from "./commercial-access";
import { requireCommercialWriteAccess, requireScopedFieldWriteAccess } from "./commercial-access";

function hash(value:string){return createHash("sha256").update(value).digest("hex");}
export async function submitFloorPlanForCustomerApproval(actor:CommercialActor,input:{organizationId:string;sessionId:string;draftId:string;userId:string;customerName?:string|null;customerEmail?:string|null}){
 const organizationId=requireCommercialWriteAccess(actor,input.organizationId.trim());
 return prisma.$transaction(async tx=>{
  const rows=await tx.$queryRaw<Array<{projectInstallationId:string;geometryJson:string;calibrationJson:string|null}>>(Prisma.sql`SELECT a.projectInstallationId,d.geometryJson,d.calibrationJson FROM SurveyFloorPlanDraft d JOIN SurveySession s ON s.id=d.sessionId AND s.organizationId=d.organizationId JOIN SurveyAssignment a ON a.id=s.assignmentId AND a.organizationId=s.organizationId WHERE d.id=${input.draftId} AND d.sessionId=${input.sessionId} AND d.organizationId=${organizationId} LIMIT 1`);
  const source=rows[0];if(!source)throw new Error("Floor plan draft not found");
  const points=await tx.$queryRaw<Array<Record<string,unknown>>>(Prisma.sql`SELECT i.id,i.surveyPointId,i.discipline,i.pointType,i.label,i.normalizedX,i.normalizedY FROM SurveyFloorPlanItem i WHERE i.organizationId=${organizationId} AND i.floorPlanDraftId=${input.draftId} ORDER BY i.createdAt`);
  const snapshot=JSON.stringify({schemaVersion:1,draftId:input.draftId,geometry:JSON.parse(source.geometryJson),calibration:source.calibrationJson?JSON.parse(source.calibrationJson):null,points});
  const snapshotHash=hash(snapshot);
  const prior=await tx.$queryRaw<Array<{revisionNumber:number}>>(Prisma.sql`SELECT revisionNumber FROM SurveyFloorPlanApproval WHERE organizationId=${organizationId} AND sessionId=${input.sessionId} ORDER BY revisionNumber DESC LIMIT 1`);
  const revisionNumber=(prior[0]?.revisionNumber??0)+1,id=randomUUID();
  await tx.$executeRaw(Prisma.sql`INSERT INTO SurveyFloorPlanApproval (id,organizationId,sessionId,floorPlanDraftId,revisionNumber,snapshotJson,snapshotHash,status,customerName,customerEmail,createdByUserId,createdAt,updatedAt) VALUES (${id},${organizationId},${input.sessionId},${input.draftId},${revisionNumber},${snapshot},${snapshotHash},'PENDING_CUSTOMER',${input.customerName?.trim()||null},${input.customerEmail?.trim()||null},${input.userId},NOW(3),NOW(3))`);
  await tx.$executeRaw(Prisma.sql`INSERT INTO ProjectActivityEvent (id,organizationId,projectInstallationId,surveySessionId,eventType,actorUserId,summary,detailsJson,occurredAt) VALUES (${randomUUID()},${organizationId},${source.projectInstallationId},${input.sessionId},'FLOOR_PLAN_SUBMITTED',${input.userId},${`Floor plan revision ${revisionNumber} submitted for customer approval`},${JSON.stringify({approvalId:id,revisionNumber,snapshotHash})},NOW(3))`);
  return {id,revisionNumber};
 });
}

export async function recordCustomerFloorPlanDecision(actor:CommercialActor,input:{organizationId:string;approvalId:string;approved:boolean;customerName:string;customerNote?:string|null;userId:string}){
 const organizationId=requireCommercialWriteAccess(actor,input.organizationId.trim());
 return prisma.$transaction(async tx=>{
  const rows=await tx.$queryRaw<Array<{id:string;sessionId:string;floorPlanDraftId:string;revisionNumber:number;projectInstallationId:string;siteId:string;snapshotJson:string}>>(Prisma.sql`SELECT ap.id,ap.sessionId,ap.floorPlanDraftId,ap.revisionNumber,a.projectInstallationId,a.siteId,ap.snapshotJson FROM SurveyFloorPlanApproval ap JOIN SurveySession s ON s.id=ap.sessionId AND s.organizationId=ap.organizationId JOIN SurveyAssignment a ON a.id=s.assignmentId AND a.organizationId=s.organizationId WHERE ap.id=${input.approvalId} AND ap.organizationId=${organizationId} AND ap.status='PENDING_CUSTOMER' LIMIT 1`);
  const ap=rows[0];if(!ap)throw new Error("Pending floor plan approval not found");
  const status=input.approved?"APPROVED":"CHANGES_REQUESTED";
  await tx.$executeRaw(Prisma.sql`UPDATE SurveyFloorPlanApproval SET status=${status},customerName=${input.customerName.trim()},customerNote=${input.customerNote?.trim()||null},approvedAt=${input.approved?new Date():null},decisionRecordedByUserId=${input.userId},customerDecisionAt=NOW(3),updatedAt=NOW(3) WHERE id=${ap.id} AND organizationId=${organizationId}`);
  let workOrderId:string|null=null;
  if(input.approved){workOrderId=randomUUID();await tx.$executeRaw(Prisma.sql`INSERT INTO ProjectWorkOrder (id,organizationId,projectInstallationId,siteId,surveySessionId,floorPlanApprovalId,title,status,customerNote,createdByUserId,createdAt,updatedAt) VALUES (${workOrderId},${organizationId},${ap.projectInstallationId},${ap.siteId},${ap.sessionId},${ap.id},${`Installation Work Order - Floor Plan R${ap.revisionNumber}`},'READY',${input.customerNote?.trim()||null},${input.userId},NOW(3),NOW(3))`);
   const snapshot=JSON.parse(ap.snapshotJson) as {points?:Array<{surveyPointId?:string;discipline:string;pointType:string;label?:string|null}>};let order=0;for(const p of snapshot.points??[]){await tx.$executeRaw(Prisma.sql`INSERT INTO ProjectWorkOrderItem (id,organizationId,workOrderId,sourceSurveyPointId,discipline,itemType,label,status,sortOrder,createdAt,updatedAt) VALUES (${randomUUID()},${organizationId},${workOrderId},${p.surveyPointId??null},${p.discipline},${p.pointType},${p.label??null},'PENDING',${order++},NOW(3),NOW(3))`);}}
  await tx.$executeRaw(Prisma.sql`INSERT INTO ProjectActivityEvent (id,organizationId,projectInstallationId,surveySessionId,workOrderId,eventType,actorUserId,actorName,actorType,summary,detailsJson,customerNote,occurredAt) VALUES (${randomUUID()},${organizationId},${ap.projectInstallationId},${ap.sessionId},${workOrderId},${input.approved?'FLOOR_PLAN_APPROVED':'FLOOR_PLAN_CHANGES_REQUESTED'},${input.userId},NULL,'INTERNAL_USER',${input.approved?`Customer approved floor plan revision ${ap.revisionNumber}`:`Customer requested changes to floor plan revision ${ap.revisionNumber}`},${JSON.stringify({approvalId:ap.id,revisionNumber:ap.revisionNumber,customerName:input.customerName.trim(),customerDecision:status,decisionRecordedByUserId:input.userId})},${input.customerNote?.trim()||null},NOW(3))`);
  return {status,workOrderId};
 });
}


export type FloorPlanApprovalSummary={id:string;revisionNumber:number;status:string;customerName:string|null;customerEmail:string|null;customerNote:string|null;approvedAt:Date|null;createdAt:Date};
export async function listFloorPlanApprovals(actor:CommercialActor,input:{organizationId:string;sessionId:string}){
 const organizationId=input.organizationId.trim();
 if(actor.role==="CLIENT_ADMIN"||actor.role==="VIEWER"){if(actor.organizationId!==organizationId)throw new Error("Cross-tenant approval read denied");}
 return prisma.$queryRaw<FloorPlanApprovalSummary[]>(Prisma.sql`SELECT id,revisionNumber,status,customerName,customerEmail,customerNote,approvedAt,createdAt FROM SurveyFloorPlanApproval WHERE organizationId=${organizationId} AND sessionId=${input.sessionId} ORDER BY revisionNumber DESC`);
}
export type ProjectActivitySummary={id:string;eventType:string;actorName:string|null;actorType:string;summary:string;customerNote:string|null;occurredAt:Date};
export async function listProjectActivity(actor:CommercialActor,input:{organizationId:string;sessionId:string}){
 const organizationId=input.organizationId.trim();
 if(actor.role==="CLIENT_ADMIN"||actor.role==="VIEWER"){if(actor.organizationId!==organizationId)throw new Error("Cross-tenant activity read denied");}
 return prisma.$queryRaw<ProjectActivitySummary[]>(Prisma.sql`SELECT id,eventType,actorName,actorType,summary,customerNote,occurredAt FROM ProjectActivityEvent WHERE organizationId=${organizationId} AND surveySessionId=${input.sessionId} ORDER BY occurredAt DESC`);
}


export type WorkOrderView={id:string;title:string;status:string;assignedToUserId:string|null;customerNote:string|null;createdAt:Date;items:Array<{id:string;discipline:string;itemType:string;label:string|null;areaName:string|null;status:string;pulledInstalled:boolean;terminated:boolean;testStatus:string|null;photoEvidenceRequired:boolean;technicianNote:string|null;completedByUserId:string|null;completedAt:Date|null}>};
export async function getWorkOrderBySurvey(actor:CommercialActor,input:{organizationId:string;sessionId:string}):Promise<WorkOrderView|null>{
 const organizationId=input.organizationId.trim();if(actor.role==="CLIENT_ADMIN"||actor.role==="VIEWER"){if(actor.organizationId!==organizationId)throw new Error("Cross-tenant work order read denied");}
 const orders=await prisma.$queryRaw<Array<Omit<WorkOrderView,"items">>>(Prisma.sql`SELECT id,title,status,assignedToUserId,customerNote,createdAt FROM ProjectWorkOrder WHERE organizationId=${organizationId} AND surveySessionId=${input.sessionId} ORDER BY createdAt DESC LIMIT 1`);const order=orders[0];if(!order)return null;
 const items=await prisma.$queryRaw<WorkOrderView["items"]>(Prisma.sql`SELECT id,discipline,itemType,label,areaName,status,pulledInstalled,terminated,testStatus,photoEvidenceRequired,technicianNote,completedByUserId,completedAt FROM ProjectWorkOrderItem WHERE organizationId=${organizationId} AND workOrderId=${order.id} ORDER BY sortOrder,id`);
 return {...order,items};
}
export async function updateWorkOrderItem(actor:CommercialActor,input:{organizationId:string;workOrderId:string;itemId:string;pulledInstalled:boolean;terminated:boolean;testStatus?:string|null;technicianNote?:string|null;userId:string}){
 const organizationId=requireScopedFieldWriteAccess(actor,input.organizationId.trim());const testStatus=input.testStatus||null;if(testStatus&&!["PASS","FAIL","NA"].includes(testStatus))throw new Error("Invalid test status");
 return prisma.$transaction(async tx=>{const rows=await tx.$queryRaw<Array<{id:string;projectInstallationId:string;surveySessionId:string;discipline:string;itemType:string;label:string|null}>>(Prisma.sql`SELECT i.id,w.projectInstallationId,w.surveySessionId,i.discipline,i.itemType,i.label FROM ProjectWorkOrderItem i JOIN ProjectWorkOrder w ON w.id=i.workOrderId AND w.organizationId=i.organizationId WHERE i.id=${input.itemId} AND i.workOrderId=${input.workOrderId} AND i.organizationId=${organizationId} LIMIT 1`);const item=rows[0];if(!item)throw new Error("Work order item not found");
 const completed=input.pulledInstalled&&input.terminated&&testStatus==="PASS";const status=testStatus==="FAIL"?"ISSUE":completed?"COMPLETED":input.pulledInstalled||input.terminated||testStatus?"IN_PROGRESS":"PENDING";
 const previous=await tx.$queryRaw<Array<{pulledInstalled:boolean;terminated:boolean;testStatus:string|null}>>(Prisma.sql`SELECT pulledInstalled,terminated,testStatus FROM ProjectWorkOrderItem WHERE id=${input.itemId} AND workOrderId=${input.workOrderId} AND organizationId=${organizationId} LIMIT 1`);
 const prev=previous[0];if(!prev)throw new Error("Work order item state not found");
 await tx.$executeRaw(Prisma.sql`UPDATE ProjectWorkOrderItem SET pulledInstalled=${input.pulledInstalled},terminated=${input.terminated},testStatus=${testStatus},technicianNote=${input.technicianNote?.trim()||null},status=${status},completedByUserId=${completed?input.userId:null},completedAt=${completed?new Date():null},updatedAt=NOW(3) WHERE id=${input.itemId} AND workOrderId=${input.workOrderId} AND organizationId=${organizationId}`);
 const stages:Array<{stage:string;result:string|null}>=[];if(prev.pulledInstalled!==input.pulledInstalled)stages.push({stage:"PULLED_INSTALLED",result:input.pulledInstalled?"DONE":"REOPENED"});if(prev.terminated!==input.terminated)stages.push({stage:"TERMINATED",result:input.terminated?"DONE":"REOPENED"});if(prev.testStatus!==testStatus)stages.push({stage:"TESTED",result:testStatus});for(const stage of stages)await tx.$executeRaw(Prisma.sql`INSERT INTO ProjectWorkOrderItemEvent (id,organizationId,workOrderId,workOrderItemId,stage,result,actorUserId,note,occurredAt) VALUES (${randomUUID()},${organizationId},${input.workOrderId},${input.itemId},${stage.stage},${stage.result},${input.userId},${input.technicianNote?.trim()||null},NOW(3))`);
 await tx.$executeRaw(Prisma.sql`INSERT INTO ProjectActivityEvent (id,organizationId,projectInstallationId,surveySessionId,workOrderId,eventType,actorUserId,summary,detailsJson,occurredAt) VALUES (${randomUUID()},${organizationId},${item.projectInstallationId},${item.surveySessionId},${input.workOrderId},'WORK_ORDER_ITEM_UPDATED',${input.userId},${`${item.label||item.itemType} updated: ${status}`},${JSON.stringify({itemId:item.id,discipline:item.discipline,itemType:item.itemType,pulledInstalled:input.pulledInstalled,terminated:input.terminated,testStatus,status})},NOW(3))`);
 const counts=await tx.$queryRaw<Array<{total:bigint;done:bigint;issues:bigint}>>(Prisma.sql`SELECT COUNT(*) total,SUM(status='COMPLETED') done,SUM(status='ISSUE') issues FROM ProjectWorkOrderItem WHERE organizationId=${organizationId} AND workOrderId=${input.workOrderId}`);const count=counts[0],next=Number(count?.issues??0)>0?"ISSUE":Number(count?.total??0)>0&&Number(count?.total??0)===Number(count?.done??0)?"COMPLETED":"IN_PROGRESS";await tx.$executeRaw(Prisma.sql`UPDATE ProjectWorkOrder SET status=${next},startedAt=COALESCE(startedAt,NOW(3)),completedAt=${next==="COMPLETED"?new Date():null},updatedAt=NOW(3) WHERE id=${input.workOrderId} AND organizationId=${organizationId}`);return {status,nextWorkOrderStatus:next};});
}


export async function listWorkOrderItemEvents(actor:CommercialActor,input:{organizationId:string;workOrderId:string}){
 const organizationId=input.organizationId.trim();if(actor.role==="CLIENT_ADMIN"||actor.role==="VIEWER"){if(actor.organizationId!==organizationId)throw new Error("Cross-tenant work order event read denied");}
 return prisma.$queryRaw<Array<{id:string;workOrderItemId:string;stage:string;result:string|null;actorUserId:string;note:string|null;occurredAt:Date}>>(Prisma.sql`SELECT id,workOrderItemId,stage,result,actorUserId,note,occurredAt FROM ProjectWorkOrderItemEvent WHERE organizationId=${organizationId} AND workOrderId=${input.workOrderId} ORDER BY occurredAt DESC`);
}


export async function persistWorkOrderEvidence(actor:CommercialActor,input:{organizationId:string;workOrderId:string;itemId:string;evidenceId:string;originalName:string;mimeType:string;byteSize:number;storageKey:string;sha256:string;caption?:string|null;userId:string}){
 const organizationId=requireScopedFieldWriteAccess(actor,input.organizationId.trim());const rows=await prisma.$queryRaw<Array<{id:string;projectInstallationId:string;surveySessionId:string}>>(Prisma.sql`SELECT i.id,w.projectInstallationId,w.surveySessionId FROM ProjectWorkOrderItem i JOIN ProjectWorkOrder w ON w.id=i.workOrderId AND w.organizationId=i.organizationId WHERE i.id=${input.itemId} AND i.workOrderId=${input.workOrderId} AND i.organizationId=${organizationId} LIMIT 1`);const item=rows[0];if(!item)throw new Error("Work order item not found");
 await prisma.$transaction([prisma.$executeRaw(Prisma.sql`INSERT INTO ProjectWorkOrderEvidence (id,organizationId,workOrderId,workOrderItemId,evidenceType,originalName,mimeType,byteSize,storageKey,sha256,caption,uploadedByUserId,createdAt) VALUES (${input.evidenceId},${organizationId},${input.workOrderId},${input.itemId},'PHOTO',${input.originalName},${input.mimeType},${input.byteSize},${input.storageKey},${input.sha256},${input.caption?.trim()||null},${input.userId},NOW(3))`),prisma.$executeRaw(Prisma.sql`INSERT INTO ProjectActivityEvent (id,organizationId,projectInstallationId,surveySessionId,workOrderId,eventType,actorUserId,summary,detailsJson,occurredAt) VALUES (${randomUUID()},${organizationId},${item.projectInstallationId},${item.surveySessionId},${input.workOrderId},'WORK_ORDER_EVIDENCE_ADDED',${input.userId},'Photo evidence added to work order item',${JSON.stringify({itemId:input.itemId,evidenceId:input.evidenceId,sha256:input.sha256})},NOW(3))`)]);
}
export async function listWorkOrderEvidence(actor:CommercialActor,input:{organizationId:string;workOrderId:string}){const organizationId=input.organizationId.trim();if(actor.role==="CLIENT_ADMIN"||actor.role==="VIEWER"){if(actor.organizationId!==organizationId)throw new Error("Cross-tenant evidence read denied");}return prisma.$queryRaw<Array<{id:string;workOrderItemId:string;originalName:string;caption:string|null;uploadedByUserId:string;createdAt:Date}>>(Prisma.sql`SELECT id,workOrderItemId,originalName,caption,uploadedByUserId,createdAt FROM ProjectWorkOrderEvidence WHERE organizationId=${organizationId} AND workOrderId=${input.workOrderId} ORDER BY createdAt DESC`);}


export async function assignWorkOrderTechnician(actor:CommercialActor,input:{organizationId:string;workOrderId:string;technicianUserId:string;userId:string}){
 const organizationId=requireCommercialWriteAccess(actor,input.organizationId.trim());
 return prisma.$transaction(async tx=>{const tech=await tx.$queryRaw<Array<{displayName:string}>>(Prisma.sql`SELECT displayName FROM FieldTechnicianProfile WHERE organizationId=${organizationId} AND userId=${input.technicianUserId} AND status='ACTIVE' LIMIT 1`);if(!tech[0])throw new Error("Active field technician profile not found");
 const rows=await tx.$queryRaw<Array<{projectInstallationId:string;surveySessionId:string}>>(Prisma.sql`SELECT projectInstallationId,surveySessionId FROM ProjectWorkOrder WHERE id=${input.workOrderId} AND organizationId=${organizationId} LIMIT 1`);const wo=rows[0];if(!wo)throw new Error("Work order not found");
 await tx.$executeRaw(Prisma.sql`UPDATE ProjectWorkOrder SET assignedToUserId=${input.technicianUserId},updatedAt=NOW(3) WHERE id=${input.workOrderId} AND organizationId=${organizationId}`);
 await tx.$executeRaw(Prisma.sql`INSERT INTO ProjectActivityEvent (id,organizationId,projectInstallationId,surveySessionId,workOrderId,eventType,actorUserId,actorName,summary,detailsJson,occurredAt) VALUES (${randomUUID()},${organizationId},${wo.projectInstallationId},${wo.surveySessionId},${input.workOrderId},'WORK_ORDER_ASSIGNED',${input.userId},NULL,'Work order assigned to field technician',${JSON.stringify({technicianUserId:input.technicianUserId,technicianName:tech[0].displayName})},NOW(3))`);});
}
export async function listFieldTechnicians(actor:CommercialActor,input:{organizationId:string}){const organizationId=input.organizationId.trim();if(actor.role==="CLIENT_ADMIN"||actor.role==="VIEWER"){if(actor.organizationId!==organizationId)throw new Error("Cross-tenant technician read denied");}return prisma.$queryRaw<Array<{userId:string;displayName:string}>>(Prisma.sql`SELECT userId,displayName FROM FieldTechnicianProfile WHERE organizationId=${organizationId} AND status='ACTIVE' ORDER BY displayName`);}


export async function createPunchListItem(actor:CommercialActor,input:{organizationId:string;workOrderId:string;workOrderItemId?:string|null;title:string;description?:string|null;severity?:string|null;assignedToUserId?:string|null;userId:string}){
 const organizationId=requireCommercialWriteAccess(actor,input.organizationId.trim());if(!input.title.trim())throw new Error("Punch list title is required");const severity=(input.severity||"NORMAL").toUpperCase();if(!["LOW","NORMAL","HIGH","CRITICAL"].includes(severity))throw new Error("Invalid punch list severity");
 return prisma.$transaction(async tx=>{const rows=await tx.$queryRaw<Array<{projectInstallationId:string;surveySessionId:string}>>(Prisma.sql`SELECT projectInstallationId,surveySessionId FROM ProjectWorkOrder WHERE id=${input.workOrderId} AND organizationId=${organizationId} LIMIT 1`);const wo=rows[0];if(!wo)throw new Error("Work order not found");if(input.workOrderItemId){const item=await tx.$queryRaw<Array<{id:string}>>(Prisma.sql`SELECT id FROM ProjectWorkOrderItem WHERE id=${input.workOrderItemId} AND workOrderId=${input.workOrderId} AND organizationId=${organizationId} LIMIT 1`);if(!item[0])throw new Error("Work order item not found");}const id=randomUUID();await tx.$executeRaw(Prisma.sql`INSERT INTO ProjectPunchListItem (id,organizationId,workOrderId,workOrderItemId,title,description,severity,status,assignedToUserId,createdByUserId,createdAt,updatedAt) VALUES (${id},${organizationId},${input.workOrderId},${input.workOrderItemId||null},${input.title.trim()},${input.description?.trim()||null},${severity},'OPEN',${input.assignedToUserId||null},${input.userId},NOW(3),NOW(3))`);await tx.$executeRaw(Prisma.sql`INSERT INTO ProjectActivityEvent (id,organizationId,projectInstallationId,surveySessionId,workOrderId,eventType,actorUserId,summary,detailsJson,occurredAt) VALUES (${randomUUID()},${organizationId},${wo.projectInstallationId},${wo.surveySessionId},${input.workOrderId},'PUNCH_LIST_CREATED',${input.userId},${`Punch list item created: ${input.title.trim()}`},${JSON.stringify({punchListItemId:id,severity})},NOW(3))`);return id;});
}
export async function resolvePunchListItem(actor:CommercialActor,input:{organizationId:string;workOrderId:string;punchListItemId:string;resolutionNote?:string|null;userId:string}){
 const organizationId=requireCommercialWriteAccess(actor,input.organizationId.trim());return prisma.$transaction(async tx=>{const rows=await tx.$queryRaw<Array<{projectInstallationId:string;surveySessionId:string;title:string}>>(Prisma.sql`SELECT w.projectInstallationId,w.surveySessionId,p.title FROM ProjectPunchListItem p JOIN ProjectWorkOrder w ON w.id=p.workOrderId AND w.organizationId=p.organizationId WHERE p.id=${input.punchListItemId} AND p.workOrderId=${input.workOrderId} AND p.organizationId=${organizationId} AND p.status='OPEN' LIMIT 1`);const item=rows[0];if(!item)throw new Error("Open punch list item not found");await tx.$executeRaw(Prisma.sql`UPDATE ProjectPunchListItem SET status='RESOLVED',resolvedByUserId=${input.userId},resolvedAt=NOW(3),resolutionNote=${input.resolutionNote?.trim()||null},updatedAt=NOW(3) WHERE id=${input.punchListItemId} AND organizationId=${organizationId}`);await tx.$executeRaw(Prisma.sql`INSERT INTO ProjectActivityEvent (id,organizationId,projectInstallationId,surveySessionId,workOrderId,eventType,actorUserId,summary,detailsJson,occurredAt) VALUES (${randomUUID()},${organizationId},${item.projectInstallationId},${item.surveySessionId},${input.workOrderId},'PUNCH_LIST_RESOLVED',${input.userId},${`Punch list item resolved: ${item.title}`},${JSON.stringify({punchListItemId:input.punchListItemId})},NOW(3))`);});
}
export async function listPunchListItems(actor:CommercialActor,input:{organizationId:string;workOrderId:string}){const organizationId=input.organizationId.trim();if(actor.role==="CLIENT_ADMIN"||actor.role==="VIEWER"){if(actor.organizationId!==organizationId)throw new Error("Cross-tenant punch list read denied");}return prisma.$queryRaw<Array<{id:string;workOrderItemId:string|null;title:string;description:string|null;severity:string;status:string;assignedToUserId:string|null;resolvedAt:Date|null;resolutionNote:string|null;createdAt:Date}>>(Prisma.sql`SELECT id,workOrderItemId,title,description,severity,status,assignedToUserId,resolvedAt,resolutionNote,createdAt FROM ProjectPunchListItem WHERE organizationId=${organizationId} AND workOrderId=${input.workOrderId} ORDER BY status,createdAt DESC`);}


export async function validateWorkOrderCloseout(actor:CommercialActor,input:{organizationId:string;workOrderId:string}){
 const organizationId=input.organizationId.trim();if(actor.role==="CLIENT_ADMIN"||actor.role==="VIEWER"){if(actor.organizationId!==organizationId)throw new Error("Cross-tenant closeout read denied");}
 const [items,punch,evidence]=await Promise.all([prisma.$queryRaw<Array<{total:bigint;completed:bigint;issues:bigint;requiredEvidence:bigint}>>(Prisma.sql`SELECT COUNT(*) total,SUM(status='COMPLETED') completed,SUM(status='ISSUE') issues,SUM(photoEvidenceRequired=TRUE) requiredEvidence FROM ProjectWorkOrderItem WHERE organizationId=${organizationId} AND workOrderId=${input.workOrderId}`),prisma.$queryRaw<Array<{openCount:bigint}>>(Prisma.sql`SELECT COUNT(*) openCount FROM ProjectPunchListItem WHERE organizationId=${organizationId} AND workOrderId=${input.workOrderId} AND status='OPEN'`),prisma.$queryRaw<Array<{covered:bigint}>>(Prisma.sql`SELECT COUNT(DISTINCT e.workOrderItemId) covered FROM ProjectWorkOrderEvidence e JOIN ProjectWorkOrderItem i ON i.id=e.workOrderItemId AND i.organizationId=e.organizationId WHERE e.organizationId=${organizationId} AND e.workOrderId=${input.workOrderId} AND i.photoEvidenceRequired=TRUE`)]);
 const total=Number(items[0]?.total??0),completed=Number(items[0]?.completed??0),issues=Number(items[0]?.issues??0),openPunch=Number(punch[0]?.openCount??0),requiredEvidence=Number(items[0]?.requiredEvidence??0),evidenceCovered=Number(evidence[0]?.covered??0),missingEvidence=Math.max(0,requiredEvidence-evidenceCovered);return {ready:total>0&&completed===total&&issues===0&&openPunch===0&&missingEvidence===0,total,completed,issues,openPunch,requiredEvidence,evidenceCovered,missingEvidence};
}
export async function closeWorkOrder(actor:CommercialActor,input:{organizationId:string;workOrderId:string;userId:string}){
 const organizationId=requireCommercialWriteAccess(actor,input.organizationId.trim());const gate=await validateWorkOrderCloseout(actor,{organizationId,workOrderId:input.workOrderId});if(!gate.ready)throw new Error(`Closeout blocked: ${gate.completed}/${gate.total} items complete, ${gate.issues} item issues, ${gate.openPunch} open punch items`);
 return prisma.$transaction(async tx=>{const rows=await tx.$queryRaw<Array<{projectInstallationId:string;surveySessionId:string}>>(Prisma.sql`SELECT projectInstallationId,surveySessionId FROM ProjectWorkOrder WHERE id=${input.workOrderId} AND organizationId=${organizationId} LIMIT 1`);const wo=rows[0];if(!wo)throw new Error("Work order not found");await tx.$executeRaw(Prisma.sql`UPDATE ProjectWorkOrder SET status='CLOSED',completedAt=COALESCE(completedAt,NOW(3)),updatedAt=NOW(3) WHERE id=${input.workOrderId} AND organizationId=${organizationId}`);await tx.$executeRaw(Prisma.sql`INSERT INTO ProjectActivityEvent (id,organizationId,projectInstallationId,surveySessionId,workOrderId,eventType,actorUserId,summary,detailsJson,occurredAt) VALUES (${randomUUID()},${organizationId},${wo.projectInstallationId},${wo.surveySessionId},${input.workOrderId},'WORK_ORDER_CLOSED',${input.userId},'Work order passed closeout gate and was closed',${JSON.stringify(gate)},NOW(3))`);});
}


export async function recordFinalAcceptance(actor:CommercialActor,input:{organizationId:string;workOrderId:string;customerName:string;customerEmail?:string|null;customerNote?:string|null;accepted:boolean;userId:string}){
 const organizationId=requireCommercialWriteAccess(actor,input.organizationId.trim());if(!input.customerName.trim())throw new Error("Customer approver name is required");const gate=await validateWorkOrderCloseout(actor,{organizationId,workOrderId:input.workOrderId});if(input.accepted&&!gate.ready)throw new Error("Final acceptance is blocked until the work order passes closeout");
 return prisma.$transaction(async tx=>{const rows=await tx.$queryRaw<Array<{projectInstallationId:string;surveySessionId:string}>>(Prisma.sql`SELECT projectInstallationId,surveySessionId FROM ProjectWorkOrder WHERE id=${input.workOrderId} AND organizationId=${organizationId} LIMIT 1`);const wo=rows[0];if(!wo)throw new Error("Work order not found");const existing=await tx.$queryRaw<Array<{id:string}>>(Prisma.sql`SELECT id FROM ProjectFinalAcceptance WHERE organizationId=${organizationId} AND workOrderId=${input.workOrderId} LIMIT 1`);const id=existing[0]?.id??randomUUID(),status=input.accepted?"ACCEPTED":"CHANGES_REQUESTED";if(existing[0])await tx.$executeRaw(Prisma.sql`UPDATE ProjectFinalAcceptance SET status=${status},customerName=${input.customerName.trim()},customerEmail=${input.customerEmail?.trim()||null},customerNote=${input.customerNote?.trim()||null},acceptedAt=${input.accepted?new Date():null},decisionRecordedByUserId=${input.userId},customerDecisionAt=NOW(3),updatedAt=NOW(3) WHERE id=${id} AND organizationId=${organizationId}`);else await tx.$executeRaw(Prisma.sql`INSERT INTO ProjectFinalAcceptance (id,organizationId,workOrderId,status,customerName,customerEmail,customerNote,acceptedAt,decisionRecordedByUserId,customerDecisionAt,createdByUserId,createdAt,updatedAt) VALUES (${id},${organizationId},${input.workOrderId},${status},${input.customerName.trim()},${input.customerEmail?.trim()||null},${input.customerNote?.trim()||null},${input.accepted?new Date():null},${input.userId},NOW(3),${input.userId},NOW(3),NOW(3))`);
 await tx.$executeRaw(Prisma.sql`INSERT INTO ProjectActivityEvent (id,organizationId,projectInstallationId,surveySessionId,workOrderId,eventType,actorUserId,actorName,actorType,summary,customerNote,detailsJson,occurredAt) VALUES (${randomUUID()},${organizationId},${wo.projectInstallationId},${wo.surveySessionId},${input.workOrderId},${input.accepted?"FINAL_ACCEPTANCE_RECORDED":"FINAL_ACCEPTANCE_CHANGES_REQUESTED"},${input.userId},NULL,'INTERNAL_USER',${input.accepted?"Customer final acceptance recorded":"Customer requested final changes"},${input.customerNote?.trim()||null},${JSON.stringify({acceptanceId:id,customerName:input.customerName.trim(),customerDecision:status,decisionRecordedByUserId:input.userId})},NOW(3))`);return id;});
}
export async function generateCloseoutPackageManifest(actor:CommercialActor,input:{organizationId:string;workOrderId:string;userId:string}){
 const organizationId=requireCommercialWriteAccess(actor,input.organizationId.trim());const gate=await validateWorkOrderCloseout(actor,{organizationId,workOrderId:input.workOrderId});if(!gate.ready)throw new Error("Closeout package blocked until all work and punch items pass");
 const wo=(await prisma.$queryRaw<Array<{projectInstallationId:string;surveySessionId:string;floorPlanApprovalId:string}>>(Prisma.sql`SELECT projectInstallationId,surveySessionId,floorPlanApprovalId FROM ProjectWorkOrder WHERE id=${input.workOrderId} AND organizationId=${organizationId} LIMIT 1`))[0];if(!wo)throw new Error("Work order not found");const acceptance=(await prisma.$queryRaw<Array<{id:string;status:string;customerName:string|null;acceptedAt:Date|null}>>(Prisma.sql`SELECT id,status,customerName,acceptedAt FROM ProjectFinalAcceptance WHERE organizationId=${organizationId} AND workOrderId=${input.workOrderId} AND status='ACCEPTED' LIMIT 1`))[0];if(!acceptance)throw new Error("Accepted final acceptance is required");
 const [items,punch,evidence,events,approval]=await Promise.all([prisma.$queryRaw(Prisma.sql`SELECT id,sourceSurveyPointId,discipline,itemType,label,areaName,status,pulledInstalled,terminated,testStatus,technicianNote,completedByUserId,completedAt FROM ProjectWorkOrderItem WHERE organizationId=${organizationId} AND workOrderId=${input.workOrderId} ORDER BY sortOrder,id`),prisma.$queryRaw(Prisma.sql`SELECT id,title,severity,status,resolvedAt,resolutionNote FROM ProjectPunchListItem WHERE organizationId=${organizationId} AND workOrderId=${input.workOrderId} ORDER BY createdAt`),prisma.$queryRaw(Prisma.sql`SELECT id,workOrderItemId,originalName,mimeType,byteSize,storageKey,sha256,caption,uploadedByUserId,createdAt FROM ProjectWorkOrderEvidence WHERE organizationId=${organizationId} AND workOrderId=${input.workOrderId} ORDER BY createdAt`),prisma.$queryRaw(Prisma.sql`SELECT eventType,actorUserId,actorName,actorType,summary,customerNote,occurredAt FROM ProjectActivityEvent WHERE organizationId=${organizationId} AND workOrderId=${input.workOrderId} ORDER BY occurredAt`),prisma.$queryRaw(Prisma.sql`SELECT id,revisionNumber,snapshotHash,snapshotJson,status,customerName,approvedAt FROM SurveyFloorPlanApproval WHERE id=${wo.floorPlanApprovalId} AND organizationId=${organizationId} LIMIT 1`)]);
 const manifest={schemaVersion:1,generatedAt:new Date().toISOString(),projectInstallationId:wo.projectInstallationId,surveySessionId:wo.surveySessionId,workOrderId:input.workOrderId,approvedFloorPlan:(approval as unknown[])[0]??null,finalAcceptance:acceptance,gate,items,punchList:punch,evidence,activity:events};const manifestJson=JSON.stringify(manifest,(_k,v)=>typeof v==="bigint"?v.toString():v);const manifestHash=createHash("sha256").update(manifestJson).digest("hex");const versionRows=await prisma.$queryRaw<Array<{version:number|null}>>(Prisma.sql`SELECT MAX(packageVersion) version FROM ProjectCloseoutPackage WHERE organizationId=${organizationId} AND workOrderId=${input.workOrderId}`);const version=Number(versionRows[0]?.version??0)+1,id=randomUUID();await prisma.$executeRaw(Prisma.sql`INSERT INTO ProjectCloseoutPackage (id,organizationId,projectInstallationId,surveySessionId,workOrderId,finalAcceptanceId,packageVersion,status,manifestJson,manifestHash,generatedByUserId,generatedAt) VALUES (${id},${organizationId},${wo.projectInstallationId},${wo.surveySessionId},${input.workOrderId},${acceptance.id},${version},'GENERATED',${manifestJson},${manifestHash},${input.userId},NOW(3))`);return {id,version,manifestHash};
}


export async function getFinalAcceptanceAndCloseout(actor:CommercialActor,input:{organizationId:string;workOrderId:string}){
 const organizationId=input.organizationId.trim();if(actor.role==="CLIENT_ADMIN"||actor.role==="VIEWER"){if(actor.organizationId!==organizationId)throw new Error("Cross-tenant final acceptance read denied");}
 const [acceptance,packages,gate]=await Promise.all([prisma.$queryRaw<Array<{id:string;status:string;customerName:string|null;customerEmail:string|null;customerNote:string|null;acceptedAt:Date|null;decisionRecordedByUserId:string|null;customerDecisionAt:Date|null;updatedAt:Date}>>(Prisma.sql`SELECT id,status,customerName,customerEmail,customerNote,acceptedAt,decisionRecordedByUserId,customerDecisionAt,updatedAt FROM ProjectFinalAcceptance WHERE organizationId=${organizationId} AND workOrderId=${input.workOrderId} LIMIT 1`),prisma.$queryRaw<Array<{id:string;packageVersion:number;status:string;manifestHash:string;generatedByUserId:string;generatedAt:Date}>>(Prisma.sql`SELECT id,packageVersion,status,manifestHash,generatedByUserId,generatedAt FROM ProjectCloseoutPackage WHERE organizationId=${organizationId} AND workOrderId=${input.workOrderId} ORDER BY packageVersion DESC`),validateWorkOrderCloseout(actor,input)]);
 return {acceptance:acceptance[0]??null,packages,gate};
}
