ALTER TABLE DesignFloor
  ADD COLUMN backgroundOpacity DECIMAL(5,4) NOT NULL DEFAULT 0.6500,
  ADD COLUMN backgroundVisible BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN backgroundLocked BOOLEAN NOT NULL DEFAULT TRUE;
