"use client";

import { useMemo, useState } from "react";
import type { CanvasElement } from "../../lib/contractor-os/design-canvas-state";
import { topologyToSvg } from "../../lib/contractor-os/network-topology-export";
import { autoLayoutTopology, generateTopology, topologyExportRows, type TopologyPositionOverrides } from "../../lib/contractor-os/network-topology";

function csvCell(value: string) { return `"${value.replace(/"/g, '""')}"`; }
function download(blob: Blob, filename: string) { const url = URL.createObjectURL(blob); const anchor = window.document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); }

export function NetworkTopologyPanel({ elements }: { elements: CanvasElement[] }) {
  const [overrides, setOverrides] = useState<TopologyPositionOverrides>({});
  const source = useMemo(() => generateTopology(elements, overrides), [elements, overrides]);
  const document = useMemo(() => ({ ...source, nodes: autoLayoutTopology(source.nodes).map((node) => overrides[node.id] ? { ...node, position: overrides[node.id] } : node) }), [source, overrides]);
  function exportCsv() { const rows = topologyExportRows(document); const csv = ["Node,IP,VLAN,Segment,Connected To", ...rows.map((row) => [row.label, row.ipAddress, row.vlan, row.segment, row.connectedTo].map(csvCell).join(","))].join("\n"); download(new Blob([csv], { type: "text/csv;charset=utf-8" }), "network-topology-closeout.csv"); }
  function exportSvg() { download(new Blob([topologyToSvg(document)], { type: "image/svg+xml;charset=utf-8" }), "network-topology.svg"); }
  function exportJpg() { const svg = topologyToSvg(document); const image = new Image(); const url = URL.createObjectURL(new Blob([svg], { type: "image/svg+xml" })); image.onload = () => { const canvas = window.document.createElement("canvas"); canvas.width = image.width; canvas.height = image.height; canvas.getContext("2d")?.drawImage(image, 0, 0); canvas.toBlob((blob) => { if (blob) download(blob, "network-topology.jpg"); URL.revokeObjectURL(url); }, "image/jpeg", 0.92); }; image.src = url; }
  function exportPdf() { const popup = window.open("", "_blank", "noopener,noreferrer"); if (!popup) return; popup.document.write(`<!doctype html><html><head><title>Network Topology</title><style>html,body{margin:0;background:#fff}svg{max-width:100%;height:auto}@page{size:landscape;margin:0.35in}</style></head><body>${topologyToSvg(document)}</body></html>`); popup.document.close(); popup.focus(); window.setTimeout(() => popup.print(), 250); }
  return <section aria-label="Network topology" className="rounded-lg border border-slate-700 bg-slate-950/60 p-3 text-sm text-slate-200"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><strong>Network Topology</strong><div className="text-xs text-slate-400">{document.nodes.length} nodes · {document.links.length} links</div></div><div className="flex gap-1"><button type="button" onClick={exportCsv} disabled={!document.nodes.length} className="rounded border border-slate-600 px-2 py-1 text-xs disabled:opacity-40">CSV</button><button type="button" onClick={exportSvg} disabled={!document.nodes.length} className="rounded border border-slate-600 px-2 py-1 text-xs disabled:opacity-40">SVG</button><button type="button" onClick={exportJpg} disabled={!document.nodes.length} className="rounded border border-slate-600 px-2 py-1 text-xs disabled:opacity-40">JPG</button><button type="button" onClick={exportPdf} disabled={!document.nodes.length} className="rounded border border-slate-600 px-2 py-1 text-xs disabled:opacity-40">PDF</button></div></div>{!document.nodes.length ? <p className="text-xs text-slate-400">Place network/security devices to generate topology.</p> : <div className="space-y-2">{document.nodes.map((node) => <div key={node.id} className="rounded border border-slate-800 p-2"><div className="font-medium">{node.label}</div><div className="text-xs text-slate-400">{[node.ipAddress, node.vlan ? `VLAN ${node.vlan}` : "", node.segment].filter(Boolean).join(" · ") || "Addressing not assigned"}</div><div className="mt-1 flex gap-1"><button type="button" className="rounded border border-slate-700 px-1.5 py-0.5 text-[11px]" onClick={() => setOverrides((current) => ({ ...current, [node.id]: { x: node.position.x - 40, y: node.position.y } }))}>←</button><button type="button" className="rounded border border-slate-700 px-1.5 py-0.5 text-[11px]" onClick={() => setOverrides((current) => ({ ...current, [node.id]: { x: node.position.x + 40, y: node.position.y } }))}>→</button></div></div>)}</div>}</section>;
}
