CREATE TABLE IF NOT EXISTS ProjectWorkOrderCloseoutRequirement (
  id VARCHAR(191) NOT NULL,
  organizationId VARCHAR(191) NOT NULL,
  workOrderId VARCHAR(191) NOT NULL,
  requireDailyClose BOOLEAN NOT NULL DEFAULT false,
  requireMaterialReturnAcknowledgement BOOLEAN NOT NULL DEFAULT false,
  requireWorkAreaPhotos BOOLEAN NOT NULL DEFAULT true,
  requireTesterEvidenceForNewRuns BOOLEAN NOT NULL DEFAULT true,
  warrantyRequired BOOLEAN NOT NULL DEFAULT false,
  warrantyStartDate DATETIME(3) NULL,
  warrantyTerms TEXT NULL,
  materialReturnRequired BOOLEAN NOT NULL DEFAULT false,
  materialReturnAcknowledged BOOLEAN NOT NULL DEFAULT false,
  materialReturnNote TEXT NULL,
  toolsRemoved BOOLEAN NULL,
  corridorsClear BOOLEAN NULL,
  workAreaPhotosSaved BOOLEAN NULL,
  buildingSecured BOOLEAN NULL,
  dailyCloseVerifiedByUserId VARCHAR(191) NULL,
  dailyCloseVerifiedAt DATETIME(3) NULL,
  technicianSignOffName VARCHAR(191) NULL,
  technicianSignOffAt DATETIME(3) NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY ProjectWorkOrderCloseoutRequirement_org_workOrder_key (organizationId, workOrderId),
  KEY ProjectWorkOrderCloseoutRequirement_workOrder_idx (workOrderId)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
